export const whoOrganizes = [
  { label: "Organizer 1", value: "Organizer 2" },
  { label: "Organizer 2", value: "Organizer 2" },
];
export const terms = [
  { label: "CREDIT - 30 Days", value: "Credit - 30 Days" },
  { label: "CREDIT - 60 Days", value: "Credit - 60 Days" },
  { label: "CREDIT - 90 Days", value: "Credit - 90 Days" },
  { label: "CREDIT - 120 Days", value: "Credit - 120 Days" },
  { label: "PROFORMA", value: "proforma" },
  { label: "LC", value: "lc" },
  { label: "CREDIT", value: "credit" },
  { label: "NA", value: "na" },
];

export const AdditionalChargesColumns = [
  // {
  //   key_name: "id",
  //   display_name: "Item ID",
  //   data_type: "int",
  //   width: 30,
  //   is_clickable: false,
  //   is_highlighted: false
  // },
  {
    key_name: "item",
    display_name: "Item",
    data_type: "string",
    width: 50,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "cost_per_unit",
    display_name: "Cost Per Unit",
    data_type: "int",
    width: 50,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "unit",
    display_name: "Units",
    data_type: "int",
    width: 50,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "total_cost",
    display_name: "Total Cost",
    data_type: "int",
    width: 50,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "action",
    display_name: "Action",
    data_type: "action",
    width: 20,
    is_clickable: true,
  },
];
export const salesOrder = {
  selectedCustomer: "",
  sales_associate: "",
  customerDetails: {
    customer_id: "",
    customer_name: "",
    invoice_address: "",
    country: "",
    state: "",
    city: "",
    postal_code: "",
    contact_name: "",
    phone_no: "",
    email: "",
    account_code: "",
    vat_no: "",
    updated_at: "",
    updated_by: "",
    payment_terms: "",
    customer_po_no: "",
    excise_registration_no: "",
    warehouse_no: "",
    eori_no: "",
    target_region: "",
  },
  shippingDetails: {
    delivery_address: "",
    country: "",
    state: "",
    city: "",
    postal_code: "",
    contact_name: "",
    phone_no: "",
    email: "",
    shipper_details: "",
    who_organizes: "",
    shipper_contact_name: "",
    shipper_phone_no: "",
    shipper_email: "",
    shipping_date: "",
    is_member_of_european_union: false,
    shipping_term: "",
  },
  productDesc: [],
  spiritAdded: [],
  new_sales_order_items: [],
  additionalCharges: [],
  supporting_documents: [],
  total_case: "",
  total_order_value: "",
  notes: "",
  special_conditions: "",
  sales_order_type: "sales_order",
};

export const addNewCustomerResp = {};

export const addSpiritMeta = [
  {
    key_name: "sl_no",
    display_name: "Sl No",
    data_type: "int",
    width: 30,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "cased_goods_id",
    display_name: "Cased Goods Id",
    data_type: "int",
    width: 30,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "brand",
    display_name: "Brand",
    data_type: "varchar",
    width: 50,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "distillery",
    display_name: "Distillery",
    data_type: "varchar",
    width: 50,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "spirit_type",
    display_name: "Spirit Type",
    data_type: "varchar",
    width: 50,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "free_item",
    display_name: "FOC Item",
    data_type: "varchar",
    width: 50,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "year",
    display_name: "Year",
    data_type: "varchar",
    width: 30,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "gift_box",
    display_name: "Gift Box",
    data_type: "varchar",
    width: 50,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "tags",
    display_name: "Tags",
    data_type: "varchar",
    width: 30,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "age",
    display_name: "Age",
    data_type: "varchar",
    width: 30,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "abv",
    display_name: "ABV (%)",
    data_type: "varchar",
    width: 30,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "cask",
    display_name: "Cask",
    data_type: "varchar",
    width: 50,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "bpc",
    display_name: "BPC",
    data_type: "varchar",
    width: 30,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "volume",
    display_name: "Volume (ltr)",
    data_type: "varchar",
    width: 30,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "cases",
    display_name: "Cases",
    data_type: "varchar",
    width: 30,
    is_clickable: false,
    is_highlighted: true,
  },
  {
    key_name: "allocations",
    display_name: "Allocations",
    data_type: "varchar",
    width: 30,
    is_clickable: true,
    is_highlighted: true,
  },
  {
    key_name: "net_cases",
    display_name: "Net Cases",
    data_type: "varchar",
    width: 30,
    is_clickable: false,
    is_highlighted: true,
  },
  {
    key_name: "bottles",
    display_name: "Bottles",
    data_type: "varchar",
    width: 30,
    is_clickable: false,
    is_highlighted: true,
  },
  {
    key_name: "loa_per_case",
    display_name: "LoA (per case)",
    data_type: "varchar",
    width: 30,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "case_reference",
    display_name: "Case Reference",
    data_type: "varchar",
    width: 50,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    key_name: "export_price",
    display_name: "Export Price",
    data_type: "varchar",
    width: 30,
    is_clickable: false,
    is_highlighted: false,
  },
  {
    display_name: "Quantity",
    key_name: "quantity",
    data_type: "string",
    width: 50,
    fixed: "right",
  },
  {
    display_name: "Case Price",
    key_name: "price_per_case",
    data_type: "string",
    width: 60,
    fixed: "right",
  },
  {
    display_name: "Total Price",
    key_name: "total_price",
    data_type: "string",
    width: 50,
    fixed: "right",
  },
  {
    display_name: "Discount (%)",
    key_name: "discount",
    data_type: "string",
    width: 50,
    fixed: "right",
  },
  {
    display_name: "Price After Discount",
    key_name: "price_after_discount",
    data_type: "string",
    width: 40,
    fixed: "right",
  },
  // {
  //   display_name: "Price After Discount",
  //   key_name: "afterDiscount",
  //   data_type: "string",
  //   width: 40,
  //   fixed: "right",
  // },
  {
    display_name: "",
    key_name: "delete-spirit",
    data_type: "",
    width: 12,
    fixed: "right",
  },
];

export const chargesMeta = [
  {
    key_name: "sl_no",
    display_name: "Sl No",
    data_type: "int",
    width: 10,
  },
  {
    display_name: "Item",
    key_name: "item",
    data_type: "string",
    width: 30,
  },
  {
    display_name: "Cost Per Unit",
    key_name: "cost_per_unit",
    data_type: "string",
    width: 30,
  },
  {
    display_name: "Unit",
    key_name: "unit",
    data_type: "string",
    width: 30,
  },
  {
    display_name: "Total",
    key_name: "total_cost",
    data_type: "string",
    width: 30,
  },
  {
    display_name: "Action",
    key_name: "delete-charges",
    data_type: "",
    width: 10,
  },
];

export const change_status = [
  {
    label: "New",
    value: "new",
  },
  {
    label: "In Progress",
    value: "in_progress",
  },
  {
    label: "Packed",
    value: "packed",
  },
  {
    label: "Shipped",
    value: "shipped",
  },
  {
    label: "Cancelled",
    value: "cancelled",
  },
];

export const documentCategoryList = [
  {
    label: "Packing List",
    value: "Packing List",
    custom_value: "packing_list",
  },
  {
    label: "Delivery Note – Unsigned",
    value: "Delivery Note – Unsigned",
    custom_value: "delivery_note_unsigned",
  },
  {
    label: "Delivery Note – Signed",
    value: "Delivery Note – Signed",
    custom_value: "delivery_note_signed",
  },
  {
    label: "Health Certificate",
    value: "Health Certificate",
    custom_value: "health_certificate",
  },
  {
    label: "Certificate of Origin",
    value: "Certificate of Origin",
    custom_value: "certificate_of_origin",
  },
  {
    label: "Certificate of Age",
    value: "Certificate of Age",
    custom_value: "certificate_of_age",
  },
  {
    label: "Invoice",
    value: "Invoice",
    custom_value: "invoice",
  },
  {
    label: "EMCS",
    value: "EMCS",
    custom_value: "emcs",
  },
  {
    label: "EUR1",
    value: "EUR1",
    custom_value: "eur1",
  },
  {
    label: "Images",
    value: "Images",
    custom_value: "images",
  },
  {
    label: "Other",
    value: "Other",
    custom_value: "other",
  },
];

export const customerSignedDocumentCategoryList = [
  // {
  //   label: "Customer Signed SOP",
  //   value: "Customer Signed SOP",
  //   custom_value: "customer_signed_sop"
  // },
  // {
  //   label: "Customer Signed AOS",
  //   value: "Customer Signed AOS",
  //   custom_value: "customer_signed_aos"
  // },
  {
    label: "Customer PO",
    value: "Customer PO",
    custom_value: "customer_po",
  },
  {
    label: "Customer Confirmation Doc",
    value: "Customer Confirmation Doc",
    custom_value: "customer_confirmation_doc",
  },
  {
    label: "Other",
    value: "Other",
    custom_value: "other",
  },
];

export const status_color_map = {
  cancelled: "#a5a5a5",
  confirmed: "#30c9ca",
  link_expired: "#fa8083",
  link_sent: "#30c9ca",
  link_viewed: "#81ba11",
  in_progress: "#ff9258",
  new: "#ffbc58",
  packed: "#30c9ca",
  pending: "#fa8083",
  shipped: "#81ba11",
  proforma_doc_sent: "#30c9ca",
  proforma_link_expired: "#fa8083",
  customer_response_yes: "#81ba11",
  customer_response_no: "#fa8083",
  confirmation_link_expired: "#fa8083",
  confirmation_doc_sent: "#30c9ca",
  confirmation_doc_viewed: "#81ba11",
  proforma_doc_viewed: "#81ba11",
  conf_doc_sent: "#30c9ca",
  conf_doc_viewed: "#81ba11",
  conf_link_expired: "#fa8083",
  cust_resp_no: "#fa8083",
  cust_resp_yes: "#81ba11",
  new: "#ffbc58",
  prof_doc_sent: "#30c9ca",
  prof_doc_viewed: "#81ba11",
  prof_link_expired: "#fa8083",
};
